### ISSUE TITLE
DV-83 ⁃ Data Processing/Identification_Amendments-to-Individual

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Features#1]
To allow changes on one aspect of an individual's detail (e,g.: "Position") without having to re-enter all the other details (i.e. "Species", "Individual" and "Gender")

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DV-83) by [Unito](https://www.unito.io)

**Comment by RossPitman** [comment]
Bump
