### ISSUE TITLE
Data Processing/Camera Trapping/Classifications/Classify: info boxes

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Features#11]
When you are in one box, an info message box appears telling you what that specific box is for (see example image below). Even though this is useful when you are getting used to the program, it becomes unnecessary and obstructive later on. So, I would suggest moving the information to a question mark (?) link that one can access whenever you want, as done with other parts.

![image](https://user-images.githubusercontent.com/44848642/48215457-e80ab880-e347-11e8-9d82-a8cefb6b85d3.png)

**Comment by RossPitman** [comment]
During a PantheraIDS workshop it was deceived to include the tooltips as standard. They equally drive me crazy, so I wish we could remove them, but for the foreseeable future we will likely need to keep them in. I want to look into a way of dynamically switching them off, but haven't figured this out yet. Going to put this on ice for now.

**Comment by rsalom** [comment]
Understood!
