### ISSUE TITLE
Data Explorer

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Features#13]
To be able to generate a map with station locations (right now the only time you can do that is when you process the images).

**Comment by RossPitman** [comment]
The new Data Explorer Maps module now has this feature. See below:

Ability to plot MCP of survey area:
<img width="1680" alt="screenshot 2018-11-23 at 08 12 44" src="https://user-images.githubusercontent.com/15226110/48930215-b8d37a00-eef7-11e8-83d2-3c7a0f5f67e1.png">

Ability to plot stations:
<img width="1680" alt="screenshot 2018-11-23 at 08 12 57" src="https://user-images.githubusercontent.com/15226110/48930224-c852c300-eef7-11e8-8c5a-12253afc5b57.png">

Ability to plot capture map, and filter to species:
<img width="1680" alt="screenshot 2018-11-23 at 08 13 15" src="https://user-images.githubusercontent.com/15226110/48930238-daccfc80-eef7-11e8-9cf2-ce9582a92d94.png">

**Comment by RossPitman** [comment]
This new feature will be part of version 1.727

**Comment by RossPitman** [comment]
I'd be interested to know what other features people may need as part of the mapping module? Keeping in mind that we're not trying to develop a GIS.

**Comment by rsalom** [comment]
Excellent! 
On a new request: How about a map with stations similar to the plot capture map, where the size of the circle represents the number of active days for that station? So, as to see geographically how was the survey effort distributed.

**Comment by RossPitman** [comment]
Will do that. Any others?

**Comment by PhilipFaure** [comment]
Completed. New layer added to explorer map to display trap effort by station.
