### ISSUE TITLE
Data Processing: Include new species for Central America

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Features#17]
Per the e-mail sent, please include the following species in IDS for Central America: 

Skunk_Spotted
Skunk_Hooded
Armadillo_Nothern_Naked-tailed
Porcupine_mexican
Dog_Bush
Raccon_Crab-eating
Weasel_Long-tailed
Anteater_Giant
Tinamou
Chachalaca_Gray_headed

**Comment by RossPitman** [comment]
These species have been added to v1.727
