### ISSUE TITLE
Data_Processing/ReferenceIndividual_account_for ID_not_tagged

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Features#22]
Unless it already exist, I believe a catch should be created to make sure each individual has at least one image saved as reference image. 
This is to avoid discrepancies between the reference database and the actual number of individual in dtbs when creating the reference database.
Would suggest that catch to be within "Identification/Manual Identification" so user can amend then and there.

**Comment by Shannon-Dubay** [comment]
This is a repeat of #23 and can be closed.
