### ISSUE TITLE
Check that all individuals have at least one reference tag

### ISSUE THREAD

**Issue by RossPitman** [pantheracorp/PantheraIDS_Features#23]
When generating a reference database, we want to ensure that all individuals have at least one tag, so that we don't propagate the non-tagged individual into the future (as another individual). To do this we need to implement a check on each database that is passed to the reference module, so that all individuals are vetted for whether they have a tag or not. If one or more individuals don't have at least one tag, the operation should be aborted.

**Comment by RossPitman** [comment]
Reference databases are no longer generated.

**Comment by Shannon-Dubay** [comment]
@RossPitman , I still think there is some important merit to this. 

This check can happen when the "Generate Reference Database" button is clicked in the "Validate" tab of Reco (however, it will be annoying for the user to only realize then that there are missing references and have to go back and run the pattern matching all over again with the missing images).
