### ISSUE TITLE
Data Analysis/Occupancy/To be able to group stations

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Features#24]
When creating detection histories, to be able to group Stations that are in the same sampling grid. For example, one sample unit may have 4 Stations, and one would want to create a detection history per grid (i.e. a 1 would appear if the species was detected in any of the 4 cameras in the grid).

 Effort file should be able to account number of days active for all cameras (i.e. if all 4 cameras where active all days, and sampling occasions are composed of 7 days, then the number of active days in that grid is 4x7=28).

**Comment by RossPitman** [comment]
Done, closed.
