### ISSUE TITLE
Data Processing/ Image Processing - Add a checking step

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Features#29]
A test was done by loading a Cameras Active sheet : 
- containing a non "CAM..." item in the CameraID column
- with columns structure in a different order (here with Site column before Study column)
- and selecting a different date format (DD/MM/YY) that the one entered in the Cameras Active sheet (DD/MM/YYYY)

and no error message was given. Would it be possible to include an error message to flag those errors/discrepancies ?

**Comment by Shannon-Dubay** [comment]
has some overlap with closed issue 81: https://github.com/pantheracorp/PantheraIDS_Issues/issues/81

**Comment by Shannon-Dubay** [comment]
Point 1 has been taken care of previously: 
![image](https://user-images.githubusercontent.com/48274721/84643274-e8910b00-aefd-11ea-8c78-908b5091cd9d.png)

Point 2 appears to not be an issue, the CA I loaded in had the "Station" column before the "Study" column and it put them in the correct places when looking at it in the "Tables" panel 

Point 3 has been taken care of previously:
![image](https://user-images.githubusercontent.com/48274721/84644376-6275c400-aeff-11ea-98ff-fded19cd54f9.png)
