### ISSUE TITLE
DataProcessing / Image Process - add error messages

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Features#32]
Would it please be possible to add an error message for : 

**1. when loading CameraActivity sheet and selecting the incorrect date format ?**
Currently it crashes when the incorrect date format is selected. FYI though if :
- selecting dd-mm-yyyy when it's actually a dd/mm/yyyy format, IDS crashes
- selecting dd/mm/yy when it's actually a dd/mm/yyyy format, IDS run (with no discrepancies in numbers of images processed)

**2. when loading CA sheet containing non "CAM...." info in the "CameraID" column (e.g, Bushnell2) or in the "Cameras" column (e.g., came1) ?**
Currently it seems IDS ignore rows with nonstandardized data entered in "CameraID" (discrepancy in numbers of images processed), same outcome when the same nonstandardized data entered in TS.
FYI though it seems IDS still handles nonstandardized data entered in "Cameras" ? -> no discrepancies in numbers of images were observed when tested, though I think that column data entry should remain standardized.

**Comment by JoleenBroadfield** [comment]
Priority tasks for coming up travel pending on this feature to be added

**Comment by RossPitman** [comment]
Implemented in version 1.13.794

**Comment by JoleenBroadfield** [comment]
Sorry Ross, when loading an incorrect CA (containing non "CAM...." info in the "CameraID" column (e.g, Bushnell2) or in the "Cameras" column (e.g., came1)), IDS (1.13.794) crashes all together now

**Comment by RossPitman** [comment]
That should be fixed in the next patch.

**Comment by RossPitman** [comment]
Version 1.13.795 released.
