### ISSUE TITLE
DataProcessing / Export Images - add error message

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Features#33]
Could an error message by added when users select the wrong image directory ?
This applies to both, Bulk Image Exporter as well as Bulk Image Exporter - Identified Individuals

Currently, IDS generate a successful message while it only created an empty folder as no images can be exported.

**Comment by JoleenBroadfield** [comment]
Priority tasks for coming up travel pending on this feature to be added

**Comment by RossPitman** [comment]
Feature coming in version 1.13.794
