### ISSUE TITLE
Process Images / Eliminate the requirement of images saving to computer

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#39]
Eliminate the requirement of having to process and save all the images onto the local computer hard drive during the Process Images / Archive Data section. This step can be limiting on computers without ample free space, and users would like to use an external hard drive in these situations.

**Comment by PhilipFaure** [comment]
Done. User able to specify external directory for archived images. Not built for merged images until issue 98 is resolved.
