### ISSUE TITLE
Data Explorer/Maps

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#42]
Would be very helpful to have the GPS coordinates show on the maps somehow- perhaps in the popup that appears once clicking on a station? If one wants to know the location of the most central station, for example, one has to load in the map, see the station which appears most central, then use the Tables module to check what the coordinates of that particular station are.

**Comment by PhilipFaure** [comment]
- coordinates displayed along with CRS and projection (top left corner)
- User able to copy coordinates to clip board by shift-control-click or control-click, MacOS and Windows, respectively.


![May-04-2020 17-11-03](https://user-images.githubusercontent.com/24668143/80981461-496ef300-8e2a-11ea-8f95-11814cc50c2b.gif)

**Comment by Shannon-Dubay** [comment]
Cool!! But how will the users know that they can shift-control-click or control-click to copy the coords?

**Comment by PhilipFaure** [comment]
@Shannon-Dubay  
Yes, there's a pop up below the map which tells them which buttons to click - can't see it in the gif unfortunately
