### ISSUE TITLE
Add MiddleEastHub as new regional hub

### ISSUE THREAD

**Issue by PhilipFaure** [pantheracorp/PantheraIDS_Features#44]
New sites and users in Saudi Arabia and existing user in Oman are currently registered under the Central Asia Hub (as it is the closest). New users to be coming soon for Saudi.

**Comment by RossPitman** [comment]
Built in the UI, but not yet implemented from the back-end. We need to complete IDS' cloud migration first.

**Comment by Shannon-Dubay** [comment]
Hi @RossPitman , 1) do you have a ROUGH timeline for when this will be finished? Marine is asking because of the saudi data that she would like to start entering soon; and 2) if marine needs to enter data before this is finished, what hub should she put data under in the meantime?

**Comment by RossPitman** [comment]
So given the urgency of this, I started working on this prior to completing the migrating process. At the moment, I think I've done everything aside from actually creating user profiles that are based in the Middle East hub. I think we were using Southern Africa as a placeholder. 

@PhilipFaure – it was Southern Africa we were using right? Can you get me a list of all the users that should be in the Middle East Hub? Thanks!

Next, I'd like to push some data into the Middle East hub for testing. @Shannon-Dubay – do we know when Marine will be ready with processed data?

**Comment by Shannon-Dubay** [comment]
Marine says they already have Check 1 from a survey, with many more coming next month. Everything will be incremental processing. 
They hope to input the check 1 and CA/TS sheets that they already have next week.

**Comment by PhilipFaure** [comment]
Hi @RossPitman 

We have gathered some data from the first site (Jabal_Uthrub) and we are hoping to process data as we go along since we need to create a report by the end of December for RCU for all sites. We are thinking of creating some nice descriptive stats plots and an shareable HTML report for them. Consequently, we will have to incrementally process the data and for some sites we will be reporting on surveys which are still running in the field. Jabal Uthrub will be taken down next month as well as one other site, whereas the other sites are coming down in January. 

Marine and I will be ready to create a database tomorrow, we will first test out the blank machine classifier, and then we will be manually classifying the rest of the images afterwards. 

The current Middle East users comprise of:
Hadi Al Hikamani (south-asia-hub) - based in Oman
Sean Carlisle (central-asia-hub) - based in UAE
Ross de Bruin (southern-africa-hub) - based in RSA
Mike Ross (southern-africa-hub) - based in RSA

**Comment by RossPitman** [comment]
Users updated to Middle East Hub.
