### ISSUE TITLE
Data Processing / Classify / Potential HotKeys

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#45]
From Joleen via the forum:
Here some quick and small suggestions [on the new image viewer in classifications module], it would great if users could use short keys to : 
- select multiple images at a time
- select all images at a time

**Comment by kacoster** [comment]
_multiple image selection hotkey_ 
(Mac) command + shift (Windows) (meta key + shift)
**Usage**
Hold the key combination and click the start and the end image

_select all images_
use select all button or _multiple image selection hotkey_
