### ISSUE TITLE
Data Explorer - Plot Colours

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#46]
From Joleen via Forum:
Not a big issue but a shame considering IDS can display such visually appealing plots 😉 : would it be possible to add a rule where [in all plots contained within Data Explorer], when one colour is used, that colour come last as choice of colour for additional species (so that the same color isn't used for two different species in a single plot)
Personal input:
I think it would be nice to be able to specify which species you want as what color. This will allow the user to ensure that certain species remain the same color throughout many different plots that they create in IDS, for consistency and easier plot interpretation in a report, paper, etc.

**Comment by Shannon-Dubay** [comment]
See Joleens forum post here for a screenshot of a plot with only 2 species shown, yet both are in the same colour. https://www.pantheraids.org/forum.html?p=post%2Factivity-pattern-choice-of-colour-in-plots-10442112%3Fpid%3D1310866942

**Comment by Shannon-Dubay** [comment]
Additional note from Jo via the forum (http://www.pantheraids.org/forum.html?p=post%2Fbroader-approach-in-data-exploreranalysis-modules-10503125%3Fpid%3D1311358278):

At the moment, if some modules allow to query multiple surveys at a time and then filter to a species level, the output remain difficult to use. For example the Map module, when pulling multiple surveys and filtering to multiple species, displays unclear visuals (e.g., same icons/colours for different species)

**Comment by PhilipFaure** [comment]
Resolved. Note, there are only so many colours before they just start being shades of each other. But there are now > 40 unique colours, and it is unlikely that an user will want to display more than 40 species on one activity patterns map? The ideas from GitHub Issue 58 will  be implemented in IDS at a later stage.

![Screenshot 2020-05-05 at 19 02 24 (2)](https://user-images.githubusercontent.com/24668143/81095360-2feea980-8f05-11ea-976f-348d2f6e93e7.png)
