### ISSUE TITLE
DV-88 ⁃ Adding attributes for IDed Individuals

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#47]
From Rebecca Wooldridge on the forum:
A suggestion for an addition to the manual identification tab / or when creating a reference database of individuals. It would be useful for us to be able to add year of first detection and site of first detection when identfying individuals. We have several long-term monitoring sites for which keeping track of when individuals were first identified is helpful. Equally, we have several individuals detected at >1 site and retaining knowledge of these landscape movements is very useful for us.
Not especially critical right now but could perhaps be a good addition in the future if it does not create too much extra work to the identifying process!
See her post here: http://www.pantheraids.org/forum.html?p=post%2Fadd-year-and-site-of-first-detection-to-identifying-individuals-10471718%3Fpid%3D1311110173

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DV-88) by [Unito](https://www.unito.io)

**Comment by PhilipFaure** [comment]
@RossPitman - can we build a new module in explorer for this, e.g. 'Individual Explorer', or something like that. This module would then do the following, users can:

1. extract data from the server for a specific individual(s),
2. visualize the data points on interactive map, and
3. generate basic descriptive stats about the individual(s) are calculated, incl. date first & last captured, site/station first & last captured at, number of sites captured at, mcp area, kde area, movement display (leaftime), other individuals that fall within the selected individual's mcp, other species captured within it's mcp, etc.

**Comment by RossPitman** [comment]
@PhilipFaure – I'd rather we built something like this within the current Data Explorer module, but keep in mind we're not working on new developments just yet. Given your imminent departure, we've got to lock down some of our unfinished tasks first.

**Comment by PhilipFaure** [comment]
Gotcha

**Comment by RossPitman** [comment]
However, the feature being requested here is more about adding the ability to add additional attributes to individuals. This should be added to the Manual Identification module. But we'll need to figure out what the best approach is. On ice for now until we've finished all existing priority tasks.
