### ISSUE TITLE
Adding "Country" attribute to table in Site Management

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#48]
Jo suggested we add a 'Country' column to the table in the Site Management module... at the moment it only has Hub, and it would be beneficial to have something that is a bit more specific.

**Comment by PhilipFaure** [comment]
Done. 
 - Added country column
 - Updated filtering functionality

![filter_countries](https://user-images.githubusercontent.com/24668143/81496193-19a26e00-92b6-11ea-9f71-df1c26087143.gif)
