### ISSUE TITLE
Data Processing/Classify - View images ordered by camera/date/time

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#50]
From Marine via the forum:
When conducting manual classification, in the Viewer, would it be possible to view the species by camera/date/time so that when we have a picture that is hard to identify (for example a piece of tail) we could use the picture(s) taken just before/after to identify the species? At the moment, it seems like the photos appear in the Viewer by date/time across all cameras. 

(for the record, I agree 100% with her- this would be great)

**Comment by PhilipFaure** [comment]
Resolved. Images are rendered in viewer in chronological order.

![Uploading Screenshot 2020-05-06 at 20.22.20 (2).png…]()
