### ISSUE TITLE
Data Processing/Classify - Select All Button

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#51]
From Marine on the forum:
When conducting manual classification, would it be possible to have a button "select all" to select all the pictures of one batch at once? It could be really useful if the classifier wrongly classifies a species as another one (for example "olive baboon" as "chacma baboon") or an object as a species (for example, a tree as an elephant trunk). 

(also, YES, would be extremely helpful)

**Comment by kacoster** [comment]
select all option added
