### ISSUE TITLE
Data Processing / Classify - Add filter for "Number of Individuals"

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#53]
From Marine on the forum (http://www.pantheraids.org/forum.html?p=post%2Fclassify-module-suggestions-10490423%3Fpid%3D1311313227):

It would be great if in Manual Classification we could filter by "Species" but also by "Station" and by "Number of individuals". That would also allow to check what the Machine Classifier put in terms of number of individuals for each pictures (if needed).

**Comment by Shannon-Dubay** [comment]
Not sure how accurate the "Number of Individuals" attribute from the machine classifier is? Is this reliable? If so, then this would be a nice addition to the filter options

**Comment by RossPitman** [comment]
It's not accurate.

**Comment by RossPitman** [comment]
But it would be useful to filter in general, even for those classifications that are manually assigned.

**Comment by RossPitman** [comment]
Done.

**Comment by Shannon-Dubay** [comment]
Just anticipating a user request:
I believe in most cases the user will want to filter to images with 1, 2, 3, 4, and possibly 5+ individuals. Once you get past 3 or 4, I don't know that selecting one integer for number of individuals is helpful. For instance, I don't know when anyone would specify they want to see images with "28" individuals in it.
Is there an easy way to change the filter options for this? Because I suspect users will suggest it

**Comment by Shannon-Dubay** [comment]
The options could also be something like: 1, 2, 3, 4, 5-10, 10-20, 30-50, 50+
