### ISSUE TITLE
DV-81 ⁃ Develop Historic data Converter tool

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#54]
From Jo on the forum: http://www.pantheraids.org/forum.html?p=post%2Fhistoric-data-converter-10503132%3Fpid%3D1311358388

As per discussion with RossPitman and Ming, historic data is a challenging topic, great value for analysis, often higher quantity compared to current surveys data, though limited accessibility. At the moment there are no tools in IDS to facilitate the incorporation of all the historic data processed in CTFM within the organisation.
In order to avoid losing this valuable data and enable teams to use/process/query/analyse it within IDS, would it be possible to include a module to allow teams from different regions to "translate"/ingest their historic data (from CTFM format to IDS standards) ?

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DV-81) by [Unito](https://www.unito.io/learn-more)

**Comment by RossPitman** [comment]
Data requested from field teams over 10 days ago. Still waiting.
