### ISSUE TITLE
Data Processing/Bulk Data Export - Clean up export columns

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#59]
When looking at the columns of the exports, there are at least 9 columns with a date-time in them, and it is not obvious what each ones signify. This is a screenshot of S2_2018 local dtbs export as an example
![image](https://user-images.githubusercontent.com/48274721/81422778-bf899780-9153-11ea-91ba-00843b1a9cbf.png)

Also, the columns are not standardized between exports from local dtbss and exports from server-based dtbss- some columns appear in one and not the other, etc.

This should be cleaned up to allow for more straightforward user use... because I am extremely familiar with IDS and the dtbs, and I'm confused by this. 👎

**Comment by Shannon-Dubay** [comment]
same goes for the independent csv exports

**Comment by RossPitman** [comment]
Done.
