### ISSUE TITLE
Data Processing / Process Images - Archive button gives user option to send dtbs to cloud

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#60]
~It would be extremely helpful to have the IDS tracker track when people create a database. This would only be on the button in the bottom left of the process images module, when users archive a database.~ 

Update: better yet, give the users an option to send their dtbs to us as soon as they create it, so that I don't have to go searching for it after the fact. Ideas discussed in meeting:

- After clicking "Archive" in the bottom left of the process module, the success popup has a button to send created dtbs and images to S3 right from that popup. This would go straight to S3 into a processed data directory. Users wouldn't have to do anything besides just click the button.
- There is also an option for the user to skip this (should they not have internet or unreliable internet), but another warning should appear informing them that they are expected to send us these two things (explicitly dtbs and images) as soon as possible, through the Unstructured Upload module. 

Additional thoughts-  would I push the new (unworked on) dtbs to Redshift then, as soon as its send through using this button? if so, is there a way for us to get notified that data were uploaded this way?

**Comment by Shannon-Dubay** [comment]
Updated idea based on our discussion today.

**Comment by RossPitman** [comment]
I'm looking into developing this today. You'd ideally push the "unworked on" dtbs to Redshift as soon as you have received it. Once pushed to Redshift, you want to validate the data using the Validation module (which you still need to be trained on).

**Comment by RossPitman** [comment]
Completed.

**Comment by Shannon-Dubay** [comment]
Hi @RossPitman, I think its worth noting that at the moment when users process their data, it usually takes longer than 10 minutes, so the security lockout screen pops up as soon as the processing is done (it never comes up in the middle of processing, it always waits until IDS is no longer thinking). Unfortunately the security popup seems to override any "Success" processing popup, so the user can't see them. This might impact user's ability to use this button.

**Comment by RossPitman** [comment]
We've enabled a feature whereby the security lockout will only activate if this modal is not active. So we won't override the existing modal anymore.
