### ISSUE TITLE
Data Processing / Recognition - Comparison Image Viewer Button Hover Labels

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#63]
When in the comparison images pop-up viewer, can the buttons at the bottom have popup names/labels when you hover over them to tell user what they do? (Like the buttons in the Cropper tool- those look really nice) 

![image](https://user-images.githubusercontent.com/48274721/82232090-675e4c80-992e-11ea-9f39-71eb8859b69d.png)

Again, not a priority at the moment.

p.s. sorry for the title of this post- I had no idea what to tell it

**Comment by kacoster** [comment]
completed
