### ISSUE TITLE
DV-77 ⁃ Data Processing / Recognition - Differentiate between comparison images needing action vs done

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#64]
When looking at all the comparison images for each primary image, can we somehow differentiate which comparison images have been confirmed or rejected already versus the ones that still need to be worked on. 

Sometimes the comparisons aren’t straightforward, and you have to work through them comparison by comparison or few by few. When doing this, it’s impossible to tell which comparisons you’ve confirmed and rejected already and which still need attention. I know you can deduce this from the table view within the information toolbox, but it is tedious. 

This could take on many forms, so I'm just going to through some ideas out... keeping in mind I have no idea how feasible these ideas are from the development end. Its just a brainstorm:

* a little symbol that appears in the upper right corner of the comparison image
  * potentially one for comparison images confirmed and another for rejected
  * OR potentially just one to show that it has been either confirmed or rejected
**- have the comparison images grey out or highlight a certain colour when they have been confirmed or rejected (exactly what is used in the cropper tool would be perfect)**
* have text appear under the image that says "Confirmed" or "Rejected" (although this is really not a good idea seeing as how we are trying to reduce clutter)

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DV-77) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://pantheradatascience.atlassian.net/secure/attachment/10094/Screenshot+2021-07-08+at+08.40.57.png">Screenshot 2021-07-08 at 08.40.57.png</a>

**Comment by Shannon-Dubay** [comment]
We have had a lot of feedback on how important this will be moving forward. 

Marike:
"My first primary image comparisons contain 131 images. I have worked through them- rejected and accepted some. I noticed that the little red square didn’t change to green (meaning that I didn’t reject/accept some of them). So I clicked on the table icon and filtered for “unvalidated” and I see that there are 5 images that still require action. **Is there a way to find these images amongst the 131 comparison images displayed somehow?**"

Stephanny via the [forum](http://www.pantheraids.org/forum.html?p=post%2Frecognitionmachine-classifier-suggestions-10575962%3Fpid%3D1311859156):
"For 'Validate', is it possible that **once you confirm or reject the comparisons, the photos change the color (so we know which ones we already did, specially when we have a lot of comparisons to check).** Something similar for when you 'cropped' the photos."

**Comment by RossPitman** [comment]
@kacoster – would we be able to add the grey highlight/overlay to the images that have all been matched/rejected, in a similar way to the cropper? I'm not sure this is even possible, given that the cropper viewer it totally different to the panel viewer.

**Comment by RossPitman** [comment]
It would be a neat solution though.

**Comment by kacoster** [comment]
Thanks, I am looking into it. I guess there is also a need for the same in the manual classification?   @RossPitman @Shannon-Dubay

**Comment by RossPitman** [comment]
Potentially, but let's just focus on this Reco component first.

**Comment by kacoster** [comment]
Developed and closed.

**Comment by Shannon-Dubay** [comment]
Highlight disappears when the images are disselected. We would need this highlight to remain active forever after the image has been confirmed or rejected y the user.
