### ISSUE TITLE
Move map from Recognition Module to Manual Identification Module

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#65]
Within reco the mapping component largely goes unused. This was (as I understand) developed to allow the user to potentially manually match images to be ID'ed spatially by plotting home ranges and other spatial information regarding individual leopards. This is generally for 'problem images', i.e. unclear images.

I argue that this is better placed within the Manual Identification module. Many of the spatial matches may be automatically made within the next step in reco (grouping), therefore making the map somewhat redundant where it is. Within the Manual Identification module, the user is manually matching based on pattern, and it makes sense that if reco has the capacity to match based on pattern and temporal-spatial information, the user should too, within the same place: Manual Identification. This leaves all the automated processed to reco, and leaves the user with the ability to manually name individuals based on patter or spatial information. The user can then manually name any individual that was considered "Unidentified" by reco, or explore named individuals that were assigned names within reco.

**Comment by Shannon-Dubay** [comment]
Marike just emailed me a question that I think directly relates to this feature request:
**Can I show the locations of individual leopards in IDS?**

After chatting with a few people who use Reco, I can confirm that the map within Reco is not utilized because IDS already automatically considers spatial-temporal information when compiling groups.

It would be great it we could move this feature into Manual Identification somewhere. 

Another thought would be to add a filter to the Map Module whereby users can not only specify species, but also individuals, to be mapped.

This can be completed when GitHub Issue 174 (map not mapping in Reco Validate tab, [here](https://github.com/pantheracorp/PantheraIDS_Issues/issues/174)) is worked on.

**Comment by RossPitman** [comment]
@Shannon-Dubay – so what I'm thinking here is to have a button somewhere within the Manual Identification module that triggers a pop-up modal to appear. This modal will basically show a big map with point locations of an individual, or many individuals, and their respective minimum convex polygons (MCPs) or kernel density estimates (KDEs).

**Comment by RossPitman** [comment]
The map will render individuals selected within the primary window and/or individuals within the secondary window, if provided. Is this what you had in mind?

**Comment by Shannon-Dubay** [comment]
Yes- I think this sounds good. There will be separate buttons for primary and secondary, right? 
Also I think its important that there is an option to download/export the map like the user can within the map module (Data Explorer).

**Comment by RossPitman** [comment]
I'm not sure. Isn't the idea to assess home range overlap for primary and secondary individuals? So both primary and secondary plots should be within one map, hence only one button some where?

**Comment by Shannon-Dubay** [comment]
ahh, I see what you are saying. Yes. Good point.

I was just thinking if users wanted to create a map that they could use in reports or give to land owners or something, they would only want one survey included. 

How difficult would it be to create 2 little checkboxes to "Show Primary" and "Show Secondary", maybe even hidden in a toolbox? They could be automatically both checked, but the user could uncheck one should they want.

**Comment by RossPitman** [comment]
I think we would include a individual based map in the explorer module should users want to export something. Rather leaving the map in manual identification to be just a map on home ranges.

**Comment by Shannon-Dubay** [comment]
Ok, yeah that would be great. I just know theres a need to export the map in the same way that the maps module can be exported, and I agree, it would go nicely in the Data Explorer module

**Comment by RossPitman** [comment]
Please confirm you are happy with this @Shannon-Dubay? The map button is here:
<img width="2325" alt="Screenshot 2020-10-23 at 07 15 53" src="https://user-images.githubusercontent.com/15226110/96960077-baea4d00-1501-11eb-936c-22956a95e906.png">

**Comment by RossPitman** [comment]
And the map renders like this:
<img width="2559" alt="Screenshot 2020-10-23 at 07 16 10" src="https://user-images.githubusercontent.com/15226110/96960106-d2c1d100-1501-11eb-9c1a-c018de98376e.png">

**Comment by RossPitman** [comment]
So in this example, the yellow MCPs are for the selected primary individuals. The blue MCP/s are for secondary individuals. On thinking about how users are likely to use this tool, we probably shouldn't be plotting the secondary MCPs. Instead, we should just plot the location (station) of where secondary image was captured (similar to the red dots). So, in using this tool, users should load their "known" individuals within the primary panel. Then the secondary panel is what they are trying to ID. They load data into the secondary panel, choose "Unidentified" in the secondary individual dropdown menu. Then the location of the image in the secondary panel is what will be plotted on the map, together with the MCPs from the primary panel. Does that make sense?

**Comment by RossPitman** [comment]
OK, this should be better. Now users can see the location of the secondary image in question, and the MCP on the primary individual selected.
![Uploading Screenshot 2020-10-23 at 08.25.50.png…]()

**Comment by RossPitman** [comment]
<img width="2559" alt="Screenshot 2020-10-23 at 08 25 50" src="https://user-images.githubusercontent.com/15226110/96963813-a0b46d00-1509-11eb-848c-54a6cdc1ccb0.png">

**Comment by RossPitman** [comment]
Users can also view multiple MCPs on the same map.
<img width="2559" alt="Screenshot 2020-10-23 at 08 29 57" src="https://user-images.githubusercontent.com/15226110/96964020-fe48b980-1509-11eb-8102-b7adb88164a6.png">

**Comment by Shannon-Dubay** [comment]
Hi @RossPitman , this looks good! I will open another GitHub Feature request for the additional "individual" filter in Maps, with an export button.

**Comment by Shannon-Dubay** [comment]
Also, what does this mean for the map within Reco? I believe we can get rid of it, but if you want to keep it then we just need to make sure it works.

**Comment by RossPitman** [comment]
The map is Reco is gone now.
