### ISSUE TITLE
When not using "external images", hide the "Browse" button

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#66]
This is NOT a priority by any means, but something that I personally think will make IDS cleaner and more user-friendly. At the moment we have a system where the user specifies if they are using external images, and if they are, then they have to browse to the images. However if they're not using external images, they ignore the browse button.
For example, this is the machine classifier:
![image](https://user-images.githubusercontent.com/48274721/84276469-ab5dff00-ab32-11ea-8ba6-5ba6a98a0594.png)

I think it would be good to only have the "Browse" button appear if the user specifies they are using external images. I'm not sure how easy this is from a development point of view, but I know we have this sort of things with other buttons within IDS. 

Modules that I can think of off the top of my head that this would simplify include: Machine Classifier, Classify, Manual Identification, Image export (although there could be some that I am forgetting). Basically anywhere where the words "External Images?" are used.

**Comment by RossPitman** [comment]
This was added to all module, apart from the classifier. Will do it asap.

**Comment by RossPitman** [comment]
Done.
