### ISSUE TITLE
DV-76 ⁃ Data Processing/Identify - develop the ability to ID multiple individuals in one image

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#67]
This would obviously take some reconstructing of the Manual Identification, Reco, and potentially Analyses sections of IDS, and perhaps the dtbss themselves. But a few users have been asking about the ability to ID multiple individuals in one image, which we currently can not do.

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DV-76) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://pantheradatascience.atlassian.net/secure/attachment/10020/Screenshot+2021-03-18+at+18.30.27.png">Screenshot 2021-03-18 at 18.30.27.png</a>

**Comment by Shannon-Dubay** [comment]
https://pantheraids.org/forum.html?p=post%2Fnaming-groupsreco-10591160%3Fdomovepost%3D1
Another post asking about how to ID multiple individuals in an image (by Becky)

**Comment by RossPitman** [comment]
IDS can now identify multiple individuals within a single image. The feature is available in the Manual Identification module, under the "Edit Secondary Image" box. It cannot be done any where else in IDS. 

The use the feature, simply add multiple options within the Gender, Individual and Position fields.  
<img width="1145" alt="Screenshot 2020-09-17 at 12 38 28" src="https://user-images.githubusercontent.com/15226110/93462213-414db680-f8e6-11ea-8eec-3c5c5d376ddc.png">

Options should be chosen in the correct order.

**Comment by Shannon-Dubay** [comment]
@RossPitman has this been pushed to alpha or beta yet? I have a list of images with multiple individuals that I can use to test the feature with.
The CB masters student will definitely want to use this feature for her spotted hyaena work as soon as its ready.

**Comment by RossPitman** [comment]
It's not available in beta or alpha yet. I can push it to beta this morning if you're keen to test further?

**Comment by RossPitman** [comment]
OK it's available in beta now BTW.

**Comment by RossPitman** [comment]
Should be version 2.26.894

**Comment by Shannon-Dubay** [comment]
Great, I will do a bit of fiddling with it either later today or tomorrow. I'll report any issues here.

**Comment by Shannon-Dubay** [comment]
I have done some testing on this (v.2.26.894 beta) with server-based images and database (S4_2019):

Image S4__Station10__Camera2__CAM40850__2019-03-20__07-14-28__1221__1 (Individual: Male_4_366 ID'ed; he is the individual on the left side of the image). 
I know from my previous notes that the individual on the right side of the image is individual Unknown_4_365.
I put the following into the "Edit Secondary Image" panel:
- Species = Leopard_African
- Gender = Unknown (Individual 2)
- Individual = 365
- Position = Left (Individual 2)

Upon clicking "Apply" I got the red thumbs down "Failed to apply edits", and the following in my log:

```
Error : All columns in a tibble must be 1d or 2d objects:
* Column `Value` is NULL
```

Thinking that maybe I first have to specify 'Individual 1' again, I try the following:
- Species = Leopard_African
- Gender = Male (Individual 1)
- Individual = 366
- Position = Right (Individual 1)

But still the same outcome.

**Comment by RossPitman** [comment]
Can you please send me the data you were using to test this? Thanks!

**Comment by Shannon-Dubay** [comment]
It's all on the server. dtbs and images. S4_2019
S4__Station10__Camera2__CAM40850__2019-03-20__07-14-28__1221__1 was the image I was working with in Manual Identification.

**Comment by Shannon-Dubay** [comment]
This still needs to be looked at- Stephanny recently posted [here](https://pantheraids.org/forum.html?p=post%2Fidentifying-2-jaguars-on-the-same-picture-11254117%3Fpid%3D1321488298) asking if we had this feature.

Also, the new options in the "gender" and "side" attributes are creating some confusion, as seen in the following forum post from Emma:
_"I get options for gender as the "female (individual 1)" and side as "left (individual 1)" without being able to just use "female" or "left" for the secondary image panel?"_

Will this cause any issues with databases if the options to label an image as "female (individual 1)" or "left (individual 1)" if the capability doesn't fully work?

Also, we need to test that we are able to delete IDs if necessary. Jo has mentioned [here](https://pantheraids.org/forum.html?p=post%2Fbug-or-new-feature-10978435%3Fpid%3D1317577655) that she wasn't able to delete multiple IDs when added accidentally. Ross suggested re-classifying the image in Classification module would erase the IDs, but this was unsuccessful.
