### ISSUE TITLE
Data Processing/Process Images- within "Image Processing" panel, add reminder to check "Graphics" panel 

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#68]
![image](https://user-images.githubusercontent.com/48274721/84421090-5649e800-ac1b-11ea-8b54-1f3d6a594a69.png)
One of the most important steps within the "Image Processing" panel (1st step) within the "Process Images" module, is that the user checks the "Graphics" panel for spatial or temporal issues with their data before processing. We find many instances where the dtbs is created with the coordinates switched, or completely incorrect. This is because the users don't remember or don't know to look at the graphics panel (and all tabs within that panel).

Please could we add a reminder somehow? This could be a short line written directly onto the page, perhaps here:
![image](https://user-images.githubusercontent.com/48274721/84421257-96a96600-ac1b-11ea-848f-860809bd51fb.png)

Or this could be located within the "Success" popup that comes up after clicking the "Scan Metadata" button. This would be ideal, since we are trying to keep the pages clean, **BUT** its worth noting that with the addition of the security timeout, users processing their data lose these popup messages because they are instantly replaced with the signin popup when processing completes. Here is what the popup looks like after successfully "scanning metadata":
![after_scan_metadata_button](https://user-images.githubusercontent.com/48274721/84505681-6ff03b80-acbe-11ea-90b3-ccd868254444.PNG)
*There is no popup after clicking Timeshift button

**Comment by RossPitman** [comment]
Please add this is the success modal that appears after scanning metadata. The security timeout shouldn't be an issue anymore.

**Comment by PhilipFaure** [comment]
Done. Please let me know of any wording changes. Clossing Issue.

<img width="1136" alt="Screenshot 2020-09-18 at 14 26 00" src="https://user-images.githubusercontent.com/24668143/93597326-27ca6e80-f9bb-11ea-9488-72dc1895c711.png">

**Comment by RossPitman** [comment]
<img width="2063" alt="Screenshot 2020-09-17 at 10 29 07" src="https://user-images.githubusercontent.com/15226110/93600420-e5eff700-f9bf-11ea-85a6-1da38b679cdb.png">
Philip please can you edit the format of the text so that it matches this new modal? We want the text to stand out. So please put the word "Important" in red, followed by bold text. Have a look at my code and just copy-paste the same approach please.

**Comment by PhilipFaure** [comment]
Done. I've changed the 'T' to lower case to be the same as the other important message (this image is before I changed to uppercase). 

<img width="1147" alt="Screenshot 2020-09-18 at 15 55 47" src="https://user-images.githubusercontent.com/24668143/93605932-b1803900-f9c7-11ea-9730-ac2a2f5894df.png">

**Comment by RossPitman** [comment]
Umm, I think you wanted to add your message to your original modal, not the one I used as an example.

**Comment by PhilipFaure** [comment]
Hey @RossPitman , there are two modalDialog messages in the data processing module. The one comes up after scanning the metadata and the other after saving the survey data into a dtbs. The first does not include your "Important: ..." message, whereas the second one does. Not sure, should I include it in both, or remove one of them entirely?

**Comment by RossPitman** [comment]
So the second modal dialog box should just have my message (not yours as well). The first one should have yours, just like you did here https://github.com/pantheracorp/PantheraIDS_Features/issues/68#issuecomment-694838715. All I was suggesting was changing the format.

**Comment by PhilipFaure** [comment]
Okay I understand what you mean, I will fix up now.

**Comment by PhilipFaure** [comment]
Message has migrated:

<img width="1440" alt="Screenshot 2020-09-21 at 08 12 13" src="https://user-images.githubusercontent.com/24668143/93736998-38a8f900-fbe2-11ea-8b64-b9f5ee33125b.png">
