### ISSUE TITLE
Revamp of Individual Reference Database

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#69]
Solutions to the ind. ref. dtbs from our discussion this morning. I have kept the numbering consistent between server vs local scenarios, for easier comparisons. 

From the server:

1. **REGULAR DTBSS**: Users will be making changes to their regular dtbss on the server. 
2. **IND REF DTBS:** Regular dtbss will automatically feed into the ind. ref. dtbs, because we will make the ind ref dtbs a "view" of the data, instead of its own entity. This way, upon "creation"/"compilation" (whats the right word?) of the view, it will always be as up to date as the dtbss on the server. The ind. ref. dtbs view will be used (as opposed to pulling directly from the regular dtbss) because it will decrease processing time, however the user will never even know it is being used- they will not have to specify it. 
3. **TO RECO, THE USER WILL NEED:** 
    1. the images (including any reference images from previous years/other sites)
    2. the dtbss (on the server) 
    * Note: They won't have to provide ind ref dtbs or even have to specify their study species (both were previously necessary), as this information can be pulled from the recognition dtbs. 
4. **IF CONSOLIDATING:** IDS will update the IDs for that individual in the current grpd.dtbs and the regular dtbss involved, which are on the server (past years/other sites?) automatically (I assume the user wouldn't have to specify these)

This would completely eliminate the need for the "Reference Database" module within "Identification", although keeping the "Explore" and "Create" tabs for admin users only would be advantageous. 

Local:

1. **REGULAR DTBSS**: Users will be making changes to their regular dtbss locally. 
2. **IND REF DTBS:** The ind. ref. dtbs will NOT be used and the information for reference images will be pulled directly from the local regular dtbss. This may increase processing time, but not a significant increase considering how long reco takes to run anyways. Since the user will need to have all the dtbss for any potential consolidating step (4 below), they are required to have all the dtbss anyways, therefore making the ind. ref. dtbs redundant. 
3. **TO RECO, THE USER WILL NEED:** 
    1. the images (including any reference images from previous years/other sites)
    2. the local dtbss (this includes all years for that site, and potentially any other site which is in close proximity)
4. **IF CONSOLIDATING:** IDS will update the IDs for that individual in the current grpd.dtbs and the regular dtbss involved, which the user would probably have to specify the location of

_**The only issue I can foresee**_ (just dawned on me while writing this post) is that a user reco-ing locally needs all the regular dtbss involved in their reco (because they may need to consolidate individuals). However, there may be a situation where the regular dtbss they need are already on the server- making any local dtbs potentially/probably outdated. This creates a situation where they would need to export the server-based dtbs into a local format so that their changes to IDs through consolidation could be incorporated. I know we are trying to avoid bringing server-based dtbss back into local format.
This impacts both step 2 and step 4 for the local user.

**Comment by RossPitman** [comment]
Re last point – we can't export a server database back to local, there's just too many issues.

**Comment by Shannon-Dubay** [comment]
If we move to a system which requires the user to be working from the server in order to use Reco, should we give the users a heads up before we implement this change? Perhaps a forum email blast?

**Comment by RossPitman** [comment]
Yep would be worth a forum notification.

**Comment by RossPitman** [comment]
Completed.
