### ISSUE TITLE
Data Processing / Process Images - Add login options to popup so users can send database&images

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#70]
Users may not have the foresight to log in to the server before processing images, but once they archive the database the popup comes up to say that they should be sending their data to us. However, if they are not already logged in, they can't- in order to make this as user-friendly as possible, is there a way to include an area to log in to the server on that actual popup? With the goal being to inconvenience the user as little as possible, so that there is a better chance they will send the data in that moment?

(also- with all these users getting this popup, they will all need server access, and soon. this means more 1password accounts as well- just something to think about)

**Comment by RossPitman** [comment]
When submitting details, the popup now includes a reminder to login to S3 and Redshift before proceeding. Hopefully this will be enough to remind users to login first before moving to the next step.
<img width="2063" alt="Screenshot 2020-09-17 at 10 29 07" src="https://user-images.githubusercontent.com/15226110/93444013-bdd59a80-f8d0-11ea-944d-941fe741f03c.png">
