### ISSUE TITLE
Data Analyses/SCR - Option to load in existing SCR input files

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#72]
From Gareth via the forum (https://pantheraids.org/forum.html?p=post%2Fscr-input-files-10611286%3Fpid%3D1312294163):

Is there any chance that we could add in an option to load existing SCR input files for analysis, rather than having to create a new set of (identical) input files each time we want to analyse data (for example if a model didn't converge and needs to be re-run with more iterations, or you want to run it with different parameters). Not a major issue but would save a bit of time and hassle. Thanks!

**Comment by PhilipFaure** [comment]
Users can load in data from csv, text, or rdata files. Closing issue.

![Screenshot 2020-09-15 at 15 50 58 (2)](https://user-images.githubusercontent.com/24668143/93219212-61a53600-f76b-11ea-95c7-6590f393f7b1.png)

**Comment by Shannon-Dubay** [comment]
@PhilipFaure what does IDS create though? Surely the user only needs the option to upload the file type that IDS created previously?
