### ISSUE TITLE
Data Processing/Process Images - Add safe catches to limit issues of incompatible metadata

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#73]
When users are entering images from non-Panthera cams or historical images which have been processed through CTFM, the chances of having "problem" metadata are high- and many times it is not obvious through looking at the basic metadata on the computer file viewer. 
Issues I have personally come across when assisting in the processing of historical data:
-Special characters in "UserComment" 
-Asian symbols in the "XPAuthor" "XPComment" and "XPTitle" for any picture taken by 3 different 2008 Cuddeback cameras

Although it is impossible to predict all metadata tags that could potentially be contained within any future images, we can at least limit the metadata issues by including a first step in the restructuring step of processing in which we remove all metadata that we won't be using.

Compliments of StarGeek on the Newbies Exif Tool forum page, apparently the following can be used to specify a list of tags to keep and delete all others:
exiftool -all= -TagsFromFile @ -TAGTOKEEP1 -TAGTOKEEP2 /path/to/files/

Upon reading the literature [here](https://exiftool.org/exiftool_pod.pdf), it appears that "-all= -tagsfromfile @" allows the user to specify that all metadata tags should be deleted except the tags following the @, when working with batches of images.

**Comment by RossPitman** [comment]
@Shannon-Dubay – please can you provide me with a bunch of images that might have these special characters/symbols? Do you have access to them? In order to test this new functionality I'm going to need a few of them. Thanks!

**Comment by RossPitman** [comment]
So I'm not sure if this will fix the issue entirely, but I've now specified a number of fields to store, and omit everything else:
-exiftoolversion 
-filename
 -directory 
-filesize 
-FileModifyDate 
-FileAccessDate 
-Make 
-Model 
-Software 
-FileType 
-FileTypeExtension 
-ImageSize 
-Megapixels 
-FileAccessDate 
-ModifyDate 
-DateTimeOriginal 
-CreateDate 
-Flash
-gpsaltitude 
-gpsDateTime 
-gpslatitude 
-gpslongitude

**Comment by RossPitman** [comment]
This omits the User Comments field, which might contain dodgy characters.

**Comment by Shannon-Dubay** [comment]
@RossPitman would you still like images to test this? Emma previously shared some images with me on dropbox when we were struggling with this that I could find for you- its only about 20 images though. 

On the other hand, I will upload a csv of an exif output created from her entire dataset. (Its saved here as an excel file so that it could be uploaded to Github). It was created using the following code:
`exiftool -r -csv \location\of\images > location\to\write\csv\to\name_of_file.csv`

If you look at the following columns, you will see what I believe was the issue: XPAuthor, XPComment, XPTitle
Once removing these three columns, the processing went much smoother.

[EXIF_OUTPUT.xlsx](https://github.com/pantheracorp/PantheraIDS_Features/files/5306571/EXIF_OUTPUT.xlsx)

**Comment by Shannon-Dubay** [comment]
The above csv was created after removing the "UserComment" column because it had a "%" in the information.
However, I would like to point out that there are special characters in many of the other columns, which were left in, and processing worked fine. So, are special characters maybe not as big of an issue as we initially thought?

For example:
"ImageDescription" column has =
"InteropIndex" has ( )
"Orientation" has ( ) 
"Warning" has [ ] 
"YCbCrSubSampling" has : ( )
