### ISSUE TITLE
Registration - Stop sending the credentials file in the automatic registration email

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#76]
When new users register for IDS they get the automated registration email containing the authentication kay and the credentials txt file- its confusing for users to get this second file because they try to load it into the signin page, or worry that they haven't done anything with the file. I know we used to require it, but now its not. Please can we either stop including this in the email, or add information within the email that tells the user they don't need to do anything with it.

**Comment by RossPitman** [comment]
Done.
