### ISSUE TITLE
Data Explorer/Descriptive Stats - Give information on how things are calculated/which packages are used

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#77]
We have had a lot of requests from users asking for more background information on how certain statistics within the Descriptive Stats section are calculated. This information could either be added to a help file (although might be difficult as there are is only one help file for the entire descriptive stats section), or it could be reported at the bottom of the page when the plot/stat is shown.

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DVLPMNT-28) by [Unito](https://www.unito.io/learn-more)

**Comment by PhilipFaure** [comment]
@RossPitman - do you recommend I create a new 'click for help' button to explain some of the stats used to calculate the descriptive statistics, or add in a new paragraph/section to the existing help file, or a button next to the export button which changes as people change their choice in the selectInput for the type of descriptive stats displayed? Or should I leave out completely?

**Comment by RossPitman** [comment]
@PhilipFaure – just add it to the existing help file.
