### ISSUE TITLE
V7 cameras have different naming format than previous versions

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#78]
From Marike via the [forum](https://pantheraids.org/forum.html?p=post%2Fprocessing-images-from-v7-cameras-and-defining-v7-nomenclature-10669440%3Fpid%3D1312777570):

I ran a survey that used about 50 x V7 cameras and the rest were V6 and V5. The V7's are named slightly differently to the older cameras: CA123456 ("CA" with 6 digits) instead of CAM12345 ("CAM" with 5 digits). 

I had to manually change all the camera folders and CA and TS sheets from "CA######" to "CAM######".

With more V7's being used in the field, perhaps we should stick to "CAM...." naming structure or include accepting "CA...." into IDS?

**Comment by RossPitman** [comment]
Yeah not sure why the M has been dropped in the newer V7s. It's very annoying.

**Comment by RossPitman** [comment]
IDS now supports CAM and CA prefixes.
