### ISSUE TITLE
Data Processing / Manual Identification - image metadata to be displayed in a more accessible format

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#79]
Feedback from Jo and Lauren via the [forum](https://pantheraids.org/forum.html?p=post%2Fchallenging-information-display-format-navigation-short-cuts-class-unidentified-10672925%3Fpid%3D1312807241). I have to say, I definitely agree with them. It makes for a lot of mouse moving and clicking, which is tedious and inefficient. I think the metadata should be displayed very simply below the image, as it was before. Perhaps only the file name, individual name, and reference needs to be shown, and the position, gender, species can be hidden in the toolbox? I know we have been trying to tidy up the pages but I feel this particular case has too many drawbacks. 

From Jo:
_Would it be possible to amend the way the information of images is displayed ? With previous version, users could see straight away the image's information, with the new version (granted visually attractive 😜) users need to do an extra step to see images' information. When this extra step need to be done for >300 images (marbled cat S33), it makes the interface usage slightly gruelling 😉. Would it be possible to revert to a more straight forward information display (full image and info) ?_

From Lauren:
_While it looks very nice, the old metadata display was easier to use than this new one. For me personally, the most valuable aspect of the metadata info is to be able to compare primary and secondary images to check for temporal matches. This is difficult to achieve when the information keeps disappearing and with the new, somewhat smaller text... just my 2 cents 😃 Thanks guys!!_

**Comment by RossPitman** [comment]
Toolboxes can now be frozen. Closed.
