### ISSUE TITLE
Develop a Database Management module for admins

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#80]
Just an idea, and I haven't fully considered how we might go about this, but it would be really amazing from an administrative point of view to have a "Database Management" module. This would include a table with:

* all created databases (which could be updated using some sort of tracking software that logs when a database is created?)
  * note: we would need to account for users which may need to process multiple times due to errors, etc. as the southern Africa hub has had to do many times in the past)
* if the database has been uploaded to the server or not (a simple yes/no, i suppose by querying what information is on redshift?)
* for server-based databases, a bit of information about them, such as whether the species observation table or individual table has data within it
* when the database was first created (can be pulled right from the trigger table) and by which user
* hub and country of database

Something like this would allow us to better understand the databases out there, what state they are in (classified? identified?), and if they are on the server. At the moment its almost impossible to know which databases are missing from the server since we don't even know what databases are created. This could also be useful for programs like the small cats program, or any other inter-regional program in the future. It would also facilitate in scientific papers/projects based which are based on only historic data (such as the CB Masters students, etc.)

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DVLPMNT-29) by [Unito](https://www.unito.io/learn-more)

**Comment by RossPitman** [comment]
So we already have points 1 and 2 built into IDS. When ever someone processes data, they send this information to Redshift automatically if connected to the internet, or on next start-up with connectivity. Info such as aborted/failed/successful/skipped database creation and or upload to Redshift, which site is was for, when and who by.

**Comment by RossPitman** [comment]
This then also covers point 4 and 5.

**Comment by RossPitman** [comment]
Just need to build a UI to render all of this...

**Comment by Shannon-Dubay** [comment]
This is fantastic! I didn't realize all that information was sent to redshift automatically- I thought the users just had the option to upload their database.... which I suspect most users will want to skip just to finish the processing module quicker.
Its not a priority, but I will await developments on this space! Sounds like my dreams come true

**Comment by RossPitman** [comment]
Development of this module has begun.
