### ISSUE TITLE
DV-72 ⁃ Add notification feature for us when user uploads data using Data Uploader Module

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#82]
Develop a way for members of the DS team to get a notification if someone uploads anything to the server using the "Data Uploader" module. (I know not all uploads will pertain to me, but for instance, its important for me to know if users are sending completed databases (species classified and individuals identified) for backup, etc.)

From Ross: "setup something that records when a user uploads data, which we can build into the Database Management module you requested" (see feature #80 )

However, it might not always be a database that the user is uploading to S3, as its unstructured. For example now a user is uploading images to help train a machine classifier, which is important for me to track but doesn't necessarily fall into the nature of the Database Management module...

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/DV-72) by [Unito](https://www.unito.io)

**Comment by RossPitman** [comment]
It's not necessarily only databases we can track. We can record when any data is uploaded via the Data Uploader module.

**Comment by RossPitman** [comment]
So we've developed a function that we can place anywhere within IDS. When this function fires it writes data to a csv, which is uploaded on next start-up. May be worth having a think about where else we might want to place this tool. Eventually we will place it almost everywhere, but for now lets think of the critical areas to monitor.

**Comment by RossPitman** [comment]
Function added to Data Uploader.

**Comment by RossPitman** [comment]
Function added to Machine Classifier.

**Comment by RossPitman** [comment]
Function added to Recognition (Run and Merge).

**Comment by RossPitman** [comment]
Function added to Bulk Image Export.

**Comment by RossPitman** [comment]
Function added to Bulk Data Export.

**Comment by RossPitman** [comment]
Function added to Data Explorer Tables and Des Stats, Explorer, Site, User, Reference Database.

**Comment by RossPitman** [comment]
Yet to add functionality to:
1. Species Management
2. Camera Management
3. Data Analysis

**Comment by Shannon-Dubay** [comment]
Yes, but that still requires one of us to manually check in the User Tracking module. I was hoping to simply be notified instead of having to remember to check it frequently.

**Comment by Shannon-Dubay** [comment]
Personally, I think the quick fix would be fine- I have my email organised so incoming emails are filed into respective email folders, so I don't think it will clog anything too much, at least for me personally. Currently, there is not much activity in that module, so it won't be many notifications. When it becomes more active perhaps then we can implement a more complex solution?
