### ISSUE TITLE
Data Processing/Manual Identification - organizational changes to the reference tag buttons

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#83]
In order to keep the three buttons related to tagging images as reference images accessible yet tidy, I propose the following changes:
- One toolbox button be shown in bold (as the one at the top left is), with the same tag icon as the tag/untag buttons currently are (not the toolbox icon like the top left). 
- Within this new button are the original buttons to tag, untag, and save tags, just as they are now.

This way, it is more obvious to the user where the tagging buttons are (before they were extremely difficult to see), but at the same time, we keep the interface less cluttered by putting the three buttons into one.

**Comment by Shannon-Dubay** [comment]
Also, while working on this, is it possible to change the toolbox icon in the top left corner to the same icon used in the bottom half of the "Validate" tab within Reco- the icon is a lowercase "i", for information, which I think should be used for any toolbox which contains metadata information, as it is in Reco.

**Comment by kacoster** [comment]
Completed

**Comment by Shannon-Dubay** [comment]
@kacoster is it possible to have the reference tag icon show up as green permanently, like the info toolbox? right now the only way a user would know its there is if they accidentally scroll over it

<img width="601" alt="Screenshot 2020-10-16 at 20 01 06" src="https://user-images.githubusercontent.com/48274721/96293097-83077500-0fea-11eb-8277-6028c87af952.png">

**Comment by kacoster** [comment]
Sorry about this @Shannon-Dubay , there are some styling files that were not copied to the recent update. I will remind Ross to include them in the next update. Thanks

**Comment by RossPitman** [comment]
Hey guys, which CSS file should I be including in the next update? @kacoster @Shannon-Dubay

**Comment by kacoster** [comment]
@RossPitman we only need to Include the recent **www/toolbox_css/spcs_idntfctn_pttrn_rcgntn_tlbx.css**.  IDS version **2.27.896** Alpha has the correct file but version **2.27.897** doesn't seem to have the correct one.

**Comment by RossPitman** [comment]
![Uploading Screenshot 2020-10-19 at 09.58.24.png…]()

**Comment by RossPitman** [comment]
Folks can we not just add the three buttons to the existing toolbox? Rather than having another toolbox. Was there a reason for separating them?

**Comment by RossPitman** [comment]
<img width="1185" alt="Screenshot 2020-10-19 at 09 58 24" src="https://user-images.githubusercontent.com/15226110/96418094-908f4b80-11f2-11eb-805a-79de33045ac8.png">

**Comment by Shannon-Dubay** [comment]
It just seems clearer from a user point of view that they would be separated because they are for different things. But I don't see any problem with putting them together I suppose.

**Comment by RossPitman** [comment]
It would just be cleaner
