### ISSUE TITLE
Data Processing / Manual Identification - unable to filter to "Left" side ref only images from mult server dtbs & images

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#85]
I am sorry for not giving more details, but with so many variables I'm not sure what the issue is.

Running v.2.26.894 beta. Using the "Primary Identifications" panel in Manual Identification.
S6 2015-2018 from the server.
Species = Leopard_African
Individual = All
Station = All
Position = Left
Images source = the server    *note: checked that all these databases have their images on the server
Clicked "Filter References", and after a few seconds the green thumbs up shows 84 reference images extracted. However, this is the same number that I get if I keep Position = All, so it seems the filtering for the position isn't working.
Upon clicking "View Primary Images", the first image I see is a Right side image, and upon clicking to the next image all I see is this:
![image](https://user-images.githubusercontent.com/48274721/95087998-aa289180-0722-11eb-8cec-bf3db0ddc50c.png)

**Comment by Shannon-Dubay** [comment]
I also thought maybe it was the Individual = All that was the problem, so instead of keeping "All", I selected every named individual (leaving out the "All", "Unidentified" and "Unknown_NA" options), and I still get the same output.

**Comment by PhilipFaure** [comment]
Done.
https://github.com/pantheracorp/PantheraIDS_v2/commit/e0c76931434aa88984f58545b78dda67825a2896
