### ISSUE TITLE
Site/Species/User Management - Mexico incorrectly placed within "centralamericahub"

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#86]
Roberto has been mentioning this for a while, but it wasn't worth looking into given our workload at that time. If things slow down, this should definitely be implemented.

The term "Mesoamerica" includes Mexico, whereas "Central America" doesn't... technically Mexico is part of North America. 

All our sites, species and users from Mexico are included incorrectly in the "centralamericahub". So, we can either change all the sites, species, and users from Mexico to the "northamericahub", or we can change the name of the "centralamericahub" to "mesoamerica". 
Which ever would be less work.

**Comment by RossPitman** [comment]
Mexico sites are now within the North America hub.

**Comment by Shannon-Dubay** [comment]
@RossPitman , see Roberto's response below. Apparently putting Mexico under northamericahub is just as unsatisfactory as putting it under 'centralamericahub' and he remains unchanged that he wants centralamericahub to be changed to mesoamericahub. What will be effected if he just keeps on using Mexico under the centralamericahub? How should I proceed- create a new feature request to change cantralamericahub to mesoamericahub and then change Mexico to mesoamericahub (HIGHLY annoying, I know)?

_Understood, although not sure if that is entirely approrpiate as Mexico is part of the Mesoamerica (former Central America) Hub. If not too complicated I will keep Mexico in Central America until the name can be changed to Mesomaerica. If it is too complicated, then don´t worry about it._

**Comment by RossPitman** [comment]
Changing to Mesoamerica is going to be a lot of work. We can get to it at some point, but not now.
