### ISSUE TITLE
User Management - Update users tab access to non-full options

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#87]
Many IDS users have full tab access, which includes unfinished modules and administrative modules (such as User Management, Backup Module, Validation module, etc.)

At the moment 30 of the 116 total IDS users have full tab access.

Also, many users that do not have "full" access still have some of these modules specified in their permissions that they shouldn't (for example, Sasi and Pap have "ct_backup" access, which is only for DS team at the moment), and many people have access to user management (which contains personal information and settings that users may not want publicly available?)

**Comment by RossPitman** [comment]
Done. Will be sent with the next version.
