### ISSUE TITLE
Reassign all "Issue Tracker" links to forum

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Features#90]
Within IDS, popups with error messages often have links to the "Issue Tracker", which link to Github. I propose we lead them instead to the forum 'home page': https://pantheraids.org/forum.html?p=categories 

<img width="1440" alt="Screenshot 2020-10-20 at 14 31 59" src="https://user-images.githubusercontent.com/48274721/96586258-096cd100-12e1-11eb-8aac-6514bf0135b2.png">

**Comment by kacoster** [comment]
Completed
